/*
 * This source file was generated by the Gradle 'init' task
 */
package de.dbhw.schachspiel;

import de.dhbw.schachspiel.Classes.Color;
import de.dhbw.schachspiel.Classes.Field;
import de.dhbw.schachspiel.Classes.Move;
import de.dhbw.schachspiel.Classes.Pieces.Pawn;
import de.dhbw.schachspiel.Classes.Pieces.Rook;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class MoveTest {
  @Test
  void PawnMove() throws Move.IllegalMoveException {
    String move = "e4";
    Move m = new Move(move, Color.WHITE);
    Assertions.assertInstanceOf(Pawn.class, m.piece);
  }
  @Test
  void IllegalMove() {
    String move = "e50";
    Assertions.assertThrows(Move.IllegalMoveException.class, () -> new Move(move, Color.WHITE));
  }
  @Test
  void normalMove() throws Move.IllegalMoveException {
    String move = "Rxd1#";
    Move m = new Move(move, Color.WHITE);
    Assertions.assertInstanceOf(Rook.class, m.piece);
    Field f = new Field(4, 0);
    Assertions.assertEquals(f,m.end);
    Assertions.assertTrue(m.isCheckmate);
  }
}
