/*
 * This source file was generated by the Gradle 'init' task
 */
package de.dhbw.schachspiel;

import de.dhbw.schachspiel.Classes.Color;
import de.dhbw.schachspiel.Classes.Game;

public class App {

  public static void main(String[] args) {
    new Game();

  }
}
