/*
 * This source file was generated by the Gradle 'init' task
 */
package de.dhbw.schachspiel;

import de.dhbw.schachspiel.classes.Game;

import java.util.Scanner;

public class App
{

    public static void main(String[] args)
    {

        String startPosition = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w";
        if (args.length == 1)
        {
            startPosition = args[0];
        }
        Scanner s = new Scanner(System.in);
        Game game = new Game(startPosition,s);
        boolean isOver = false;
        while (!isOver){
            isOver = game.play();
        }
        if (game.getWinner() == null)
        {
            System.out.println("Stalemate");
        }
        else
        {
            System.out.println(game.getWinner() + " won");
        }


    }
}
