/*
 * This source file was generated by the Gradle 'init' task
 */
package de.dhbw.schachspiel;

import de.dhbw.schachspiel.classes.Game;

public class App
{

    public static void main(String[] args)
    {
        new Game();

    }
}
