/*
 * This source file was generated by the Gradle 'init' task
 */
package de.dhbw.schachspiel;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();

    Assertions.assertEquals(12, classUnderTest.add(5, 7));
    Assertions.assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
